version: '2'
services:
  web:
    image: 754040250767.dkr.ecr.us-west-2.amazonaws.com/odoo0-dev1-or0 # fictiv-odoo:13.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ../../fictiv-odoo:/mnt/extra-addons
  db:
    image: 754040250767.dkr.ecr.us-west-2.amazonaws.com/odoodb0-dev1-or0 # postgres:10
    ports:
      - "5432:5432" # (currently not exposing this out properly to connect with local client)
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
