version: '2'
services:
  web:
    image: 754040250767.dkr.ecr.us-west-2.amazonaws.com/odoo0-dev1-or0 # odoo:13.0
    depends_on:
      - db
      - redis
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./sql:/mnt/sql
      - ./odoo-web-data:/mnt/files
      - ../../fictiv-odoo:/mnt/extra-addons
    env_file:
      - ./.env
  db:
    image: 754040250767.dkr.ecr.us-west-2.amazonaws.com/odoodb0-dev1-or0 # postgres:10
    ports:
      - "5434:5432" # exposing this out properly to connect with local client
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  redis:
    image: bitnami/redis:latest
    ports:
      - "6380:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  odoo-web-data:
  odoo-db-data:
